Feature/Support pennylane's Hamiltonian
Jij-Inc/Qamomile pull request #107
Opened 2024-11-28 03:17 UTC by ahao27

# Description
Add a new transpiler to support Pennylane's Hamiltonian format in Qamomile.
This PR introduces a transpiler specifically designed to convert Qamomile's Hamiltonians into Pennylane's Hamiltonians, enhancing the interoperability between the two quantum frameworks.

# Changes

1. Added Core Transpiler Implementation:

Implements the PennylaneTranspiler class, which handles the conversion of Qamomile's Hamiltonians into Pennylane's qml.Hamiltonian objects.

- transpiler.py:
Supports Pauli-X, Pauli-Y, and Pauli-Z operators, with appropriate error handling for unsupported cases.

- exception.py:
Introduces custom exceptions for handling unsupported operations during the transpilation process.

- __init__.py:
Allows for module initialization and ensures proper package integration.

2. Unit Tests:

Created test_pennylane_transpiler.py to validate the correctness of the transpiler.
Test cases cover:

- Basic Hamiltonians with single terms (e.g., X @ Z).
- Complex Hamiltonians with multiple terms (e.g., X @ Y + Z @ X).

3. Docstring:

Inline docstrings were added to describe the purpose and functionality of each method and class.

2024-11-28 04:13 UTC, Jacomichi requested changes
Please also fix pyproject.toml because the tests fail
https://github.com/Jij-Inc/Qamomile/blob/b1efe3c7e3bcba7b140cd465106728fffadee27c/pyproject.toml#L45-L47

2024-11-28 05:07 UTC, ahao27 commented
# Changes
[Qamomile/pyproject.toml](https://github.com/Jij-Inc/Qamomile/blob/b1efe3c7e3bcba7b140cd465106728fffadee27c/pyproject.toml#L45-L47) the `pennylane = ["pennylane"]` is added.

2024-11-28 05:46 UTC, Jacomichi requested changes
I have left the comments.

2024-11-28 05:46 UTC, Jacomichi commented on pyproject.toml
> +PennyLane = "^0.39.0"
small letter is better

2024-11-28 05:46 UTC, Jacomichi commented on pyproject.toml
> +PennyLane = ["PennyLane"]
small letter is better

2024-11-28 06:34 UTC, ahao27 commented on pyproject.toml
> +PennyLane = "^0.39.0"
FIxed

2024-11-28 06:35 UTC, ahao27 commented on pyproject.toml
> +PennyLane = ["PennyLane"]
Fixed

2024-12-02 13:17 UTC, yuyamashiro submitted a review, later dismissed

2024-12-03 01:59 UTC, Jacomichi approved these changes

2024-12-05 08:59 UTC, ahao27 commented
Here is a simple usage of the Parameter gate transfer from QamomileCircuit to pennylane Qnode.
```
from qamomile.core.circuit import QuantumCircuit as QamomileCircuit
import pennylane as qml
import numpy as np
import qamomile
from qamomile.pennylane.transpiler import PennylaneTranspiler
from qamomile.core.circuit import Parameter

qc = QamomileCircuit(3)
theta = Parameter("theta")
beta = Parameter("beta")
gamma = Parameter("gamma")

qc.rx(theta, 0)
qc.ry(beta, 1)
qc.rz(gamma, 2)
qc.crx(gamma, 0 ,1)
qc.crz(theta, 1 ,2)
qc.cry(beta, 2 ,0)

transpiler = PennylaneTranspiler()
QNode = transpiler.transpile_circuit(qc)
print("QN: ", QNode)
p= {"theta":0.1,"beta":0.2, "gamma": 0.3}
qml.drawer.use_style("black_white")
fig, ax = qml.draw_mpl(QNode)(theta=0.1,beta=0.2, gamma=0.3)
```

2024-12-11 05:31 UTC, Jacomichi requested changes
I think we should write the QAOA in this way.

```python
import qamomile.core as qm
from qamomile.pennylane.transpiler import PennylaneTranspiler

qaoa_converter = qm.qaoa.QAOAConverter(compiled_model)

qaoa_converter.ising_encode()
qaoa_hamiltonian = qaoa_converter.get_cost_hamiltonian()

p = 2
qaoa_circuit = qaoa_converter.get_qaoa_ansatz(p=p)
transpiler = PennylaneTranspiler()
circ_func = transpiler.transpile_circuit(qaoa_circuit)
qml_hamiltonian = transpiler.transpile_hamiltonian(qaoa_hamiltonian)


dev = qml.device("default.qubit", wires=qaoa_circuit.num_qubits)

@qml.qnode(dev)
def circuit(params, return_samples=False):
    circ_func(params)
    if return_samples:
        return qml.sample()
        
    return qml.expval(qml_hamiltonian)

```

2024-12-11 05:31 UTC, Jacomichi commented on qamomile/pennylane/transpiler.py
> +            ops.append(qml.operation.Tensor(*op_list))
`qml.operation.Tensor` provides a warning. Could you check it and choose a non-warning approach, please?

2025-01-03 07:06 UTC, yuyamashiro approved these changes

2025-01-17 14:50 UTC, yuyamashiro commented
Fixed `_extract_variable` so that it can evaluate any expression that can be constructed by traversing ParameterExpression.

@ahao27 
The original implementation could only evaluate linear cases, but was that intended? Please check that your current implementation matches the original intent.

2025-01-17 15:06 UTC, yuyamashiro commented
I have modified `_create_param_mapping`. Since `gate.parameters` returns `list[Parameter]`, I simplified the implementation.

https://github.com/Jij-Inc/Qamomile/blob/03627f1475014de7912f6a3ab17611af52b4177d/qamomile/pennylane/transpiler.py#L137-L150

2025-01-20 04:31 UTC, Jacomichi requested changes
Please implement `convert_result`

2025-01-20 04:31 UTC, Jacomichi commented on docs/tutorial/building_quantum_circuits.ipynb
> +    "Here's how you can execute a Qamomile circuit using Qpennylane.\n",
`Qpennylane` is typo

2025-01-20 04:31 UTC, Jacomichi commented on qamomile/pennylane/transpiler.py
> +    def convert_result(self, result: Any) -> Any:
Please implement this function to decode the sampled solutions.

2025-01-23 04:10 UTC, Jacomichi requested changes
Thanks. I have left the comments

2025-01-23 04:10 UTC, Jacomichi commented on qamomile/pennylane/transpiler.py
> +        Currently not implemented.
Can you write the docstring?
And also, can you fix the type?

2025-01-23 10:59 UTC, Jacomichi requested changes

2025-01-23 10:59 UTC, Jacomichi commented on qamomile/pennylane/transpiler.py
> +        num_bits = len(result.popitem()[0])
I think `popitem` modifies the `result`, so we should not use it.

2025-01-24 00:10 UTC, Jacomichi approved these changes
Thanks!

2025-01-24 00:42 UTC, yuyamashiro commented
👍

2025-01-24 00:42 UTC, merged